name: CrunchSiegeWeapons
main: siegeCore.CrunchSiegeCore
version: 1.0
api-version: 1.18
commands:
    crunchsiege:
        description: show event details and progress
        default: false
        usage: crunchsiege