# =================================================================
# |          SiegeEngines by C_CORP2002 & ShermansWorld           |
# |    ** Forked from CrunchSiegeEquipment by TheRealCrunch **    |
# =================================================================

# DO NOT CHANGE
config-version: 1

# =====================================
# |         GENERAL SETTINGS          |
# =====================================

