# =================================================================
# |          SiegeEngines by C_CORP2002 & ShermansWorld           |
# |    ** Forked from CrunchSiegeEquipment by TheRealCrunch **    |
# =================================================================

# DO NOT CHANGE
config-version: 1

# =====================================
# |         GENERAL SETTINGS          |
# =====================================

# The item used to aim and fire siege engines
# Must be a valid material. See https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
ControlItem: CLOCK

# The maxmimum distance the player can be away from the siege engine before total control is terminated
ControlDistance: 64

# The maximum distance the player can be away from the siege engine before rotation control is terminated
RotateDistance: 32